### ISSUE TITLE
Use decompress instead camlzip

### ISSUE THREAD

**Issue by dinosaure** [rlepigre/ocaml-imagelib#1]
Hi, may be you don't know but [Decompress](https://github.com/mirage/decompress) is a pure implementation of zlib in OCaml (only zlib at this time). So, if you use it, you can compile with `js_of_ocaml` as the last version of [`ocaml-git`](https://github.com/mirage/ocaml-git) 👍 ! I think, the integration is not so hard (we provide the _same_ high level interface than `camlzip` and we provide a good low level interface which seems to be stable).

I can help you for the integration if you want.

**Comment by rlepigre** [comment]
Why not, I'll try it when I have a moment!
