### ISSUE TITLE
Consider implementing taking in_channel instead of filename

### ISSUE THREAD

**Issue by cfcs** [rlepigre/ocaml-imagelib#2]
Hello!

Would you consider changing the `Image.ReadImage` signature to from taking a filename to taking an `in_channel` instead?

I would like to use the library on Mirage where `Pervasives.open_in_bin` is not available. :-)

**Comment by rlepigre** [comment]
Hi there !

Thanks for the suggestion, I will provide functions for writing / reading from channels as soon as I have a moment.
