### ISSUE TITLE
PNG: we should skip private chunks.

### ISSUE THREAD

**Issue by cfcs** [rlepigre/ocaml-imagelib#25]
We sometimes have trouble parsing images from imagemagick because they emit this chunk they made up themselves (?): `caNv`:
`Fatal error: exception Image.Corrupted_image("Unknown chunk type \"caNv\"...")`

Maybe we could make the parser skip that?

Here's the commit that introduces that:
https://github.com/ImageMagick/ImageMagick/commit/a9e228f8ac260e5f3a241bb5efcc35cb7a653e08

**Comment by rlepigre** [comment]
OK, seems like a bug to me. According to the standard, this qualifies as a private chunk and we should simply ignore it. A private chunk will have the fifth bit of its second byte set to 1 (making it a lowercase).
