### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by bluddy** [rlepigre/ocaml-imagelib#32]
Please make a new release. The latest release requires a specific, old version of decompress (0.7). The ones before that don't seem to compile on newer ocaml compilers.

**Comment by rlepigre** [comment]
A release has been planned for a while, but I currently don't have time to look at that. Maybe another developer can look into it.

**Comment by bluddy** [comment]
It's actually worse than I thought, since decompress 0.7 has a constraint of < ocaml 4.08.0. So since 4.08.0, Imagelib has been uninstallable. 20160413 fails on a version of camlzip which has a bytes/string confusion error.

**Comment by mseri** [comment]
What is blocking a release of the current master?

**Comment by rlepigre** [comment]
@cfcs do you want to merge #36 before we make a new release?

**Comment by yomimono** [comment]
I recognize that this isn't a democracy, but I'd like to second the request for a new release, and support the inclusion of #36 .

I don't have a ton of availability for contributing to projects these days, but if there are specific well-defined tasks that I could tackle to help make this happen, please feel free to @ me.

**Comment by rlepigre** [comment]
I'm perfectly fine making a new release, the only thing is that I don't have much time to take care of it myself. I know it is annoying that I'm not around to drive the project. It really slows it down too much. I guess one solution would be to move this repository to some community-driven organisation. Does anyone know of such a thing for OCaml?

**Comment by mseri** [comment]
There is https://github.com/ocaml-community/, we could ask @rizo or @pmetzger.
If it's just a problem of doing the release, I can help if you want

**Comment by rlepigre** [comment]
OK cool. If you want to help for the release that would be great. However it would be nice to get confirmation from @cfcs that #36 can be merged so that it can be included.

**Comment by cfcs** [comment]
@rlepigre @bluddy @mseri @yomimono 
I'm sorry for my prolonged absense; my computer died, and I was unable to login to Github. I got a replacement, but then Github wouldn't let me log in from my home address. I merged #36 and I think we are ready for a release now.

I don't know how to cut a release, but I'd be happy to assist with any green button clicking required to make that happen, if any.

**Comment by rlepigre** [comment]
No worries! Thanks again @cfcs.

If anyone wants to take care of the release, feel free to do it. I don't think this should be very hard, but there are a couple of things to figure out. For example, should there be a single package? A separate package for the unix part? I'd be in favour of having a single package, and having the unix part be installed optionally (dune allows that kind of thing if I remember correctly). Does anyone has any opinion on that?

**Comment by mseri** [comment]
Hi all, with dune it is so easy to split packages that I think it would be much better to keep the current separation into imagelib and imagelib-unix and avoid optional dependencies.

@rlepigre for what concerns the release, it should boil down to run
```
opam update && opam install dune-release
dune-release tag ocaml-imagelib_20200824
dune-release -t ocaml-imagelib_20200824 --pkg-version=20200824
```

This will take care of bundling the package, push the tags, create the release with the payloads an and make a pull request on the opam repository. You need push rights to use it, so I cannot do it myself.

Before releasing I am sending a PR to fix the opam files (https://github.com/rlepigre/ocaml-imagelib/pull/38): dune should not be a build dependency, this has to do with forward compatibility issues (https://github.com/ocaml/opam-repository/issues/14185)

EDIT: `dune-release` is slightly opinionated, I have checked if other changes were needed and added them to the PR. I tried a fake release on my fork and seems to work.

**Comment by rlepigre** [comment]
@mseri I made you a collaborator, you should have gotten an invite.

**Comment by mseri** [comment]
Got the invitation! Thanks

**Comment by cfcs** [comment]
I'd be in favor for one package, multiple findlib packages (and no optional dependencies). I don't think the extra dependencies matter much on the build systems, and it makes for an easier transition (than having to keep multiple dune packages in lock-step).

EDIT: But that's no hard opinion, I'll be fine with whatever you come up with :-)

**Comment by mseri** [comment]
`unix` cannot be used if you want to use `imagelib` in a unikernel or with `js_of_ocaml`, so if you merge everything in a package that will break unless I am mistaken. Why do you need to use multiple dune files in lock-step? As a user of the library it is just a matter of specifying which dependency you use and if you use the unix version to add `imagelib-unix` among them

**Comment by cfcs** [comment]
@mseri Sorry, I got my terminology mixed up:
For *linking* we absolutely need separate findlib/dune packages for the reasons you stated.
For *opam* it would be nice to have a single one that installed both.

 I think you would add `imagelib.unix` as a dependency in `dune` (as the `imagetool` in `app/` does, and just `imagelib` in the opam files.

**Comment by cfcs** [comment]
Here's an example of such a findlib package, `dns-client.lwt`: https://github.com/mirage/ocaml-dns/blob/master/lwt/client/dune

**Comment by mseri** [comment]
I see what you mean. I tend to like more the fine-grained packages but I don't mind either way.
@yomimono is this a problem for mirage or js_of_ocaml that you know?
@rlepigre are you ok with the change?

I have not the time to make also those changes at the moment, feel free to send a separate PR for it. I will wait until this is settled to do the release.

EDIT: Besides, I have fixed travis but it seems that imagelib is not picked up by imagelib-unix, so there may be some fixing needed there anyways

**Comment by rlepigre** [comment]
I also slightly prefer having a single package called `imagelib` and which provides two ocamlfind packages `imagelib` and `imagelib.unix`. But I am also fine with having several opam packages.

**Comment by mseri** [comment]
I added a PR unifying the libraries. Then I guess it is ready to release. My only question at this moment is if the crowbar tests is supposed to hang (as it does now) or not

**Comment by mseri** [comment]
Release pending opam-repository approval: https://github.com/ocaml/opam-repository/pull/17314/files

I am going to close this
