### ISSUE TITLE
Can not be installed with esy

### ISSUE THREAD

**Issue by dmtrKovalenko** [rlepigre/ocaml-imagelib#41]
Trying to install the following lib with https://esy.sh/ leads to build exception

1. `git clone https://github.com/esy-ocaml/hello-reason.git test-imagelib`
2. cd `test-imagelib`
3. `esy build` <- no exception here
3. `esy add @opam/imagelib`
4. `esy build`

```
info building @opam/checkseum@opam:0.2.1@426d3914
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @opam/checkseum@opam:0.2.1
    # esy-build-package: pwd: /Users/dmitrijkovalenko/.esy/3/b/opam__s__checkseum-opam__c__0.2.1-9d8b92f7
    # esy-build-package: running: 'dune' 'build' '-p' 'checkseum' '-j' '4'
    # esy-build-package: running: './install/install.ml'
    Cannot find file topfind.
    Unknown directive `require'.
    error: command failed: './install/install.ml' (exited with 2)
    esy-build-package: exiting with errors above...
```

**Comment by mseri** [comment]
This does not seem a problem of `imagelib`: it looks as if it is failing to build https://github.com/mirage/checkseum which is a dependency of decompress which is a dependency of imagelib, so very early in the chain of dependencies

**Comment by hannesm** [comment]
..and the checkseum esy issue was reported at https://github.com/mirage/checkseum/issues/48 and fixed in https://github.com/mirage/checkseum/pull/49 (pending a release to opam-repository //cc @dinosaure)

**Comment by mseri** [comment]
Ah, fantastic. I am closing this then
